create or replace TABLE CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL autoincrement,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	PHONE VARCHAR(25),
	EMAIL VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(50),
	STATE VARCHAR(25),
	ZIP_CODE VARCHAR(5),
	primary key (CUSTOMER_ID)
);
