create or replace TABLE PRODUCTS (
	PRODUCT_ID NUMBER(38,0) NOT NULL autoincrement,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	BRAND_ID NUMBER(38,0) NOT NULL,
	CATEGORY_ID NUMBER(38,0) NOT NULL,
	MODEL_YEAR NUMBER(38,0) NOT NULL,
	LIST_PRICE NUMBER(10,2) NOT NULL,
	primary key (PRODUCT_ID)
);
