create or replace TABLE STAFFS (
	STAFF_ID NUMBER(38,0) NOT NULL autoincrement,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PHONE VARCHAR(25),
	ACTIVE NUMBER(38,0) NOT NULL,
	STORE_ID NUMBER(38,0) NOT NULL,
	MANAGER_ID NUMBER(38,0),
	unique (EMAIL),
	primary key (STAFF_ID),
	foreign key (MANAGER_ID) references PETSHOP.CORE.STAFFS(STAFF_ID)
);
